login page translated
boolean-uk/team-dev-client-c11 pull request #147
Opened 2024-02-14 11:21 UTC by Faiza-tech

2024-02-14 11:28 UTC, PCapid3v reviewed
Good Job!

2024-02-14 11:30 UTC, PeachyOmnivore requested changes

2024-02-14 11:30 UTC, PeachyOmnivore commented on src/pages/login/index.js
> +              label={`${t('email')} *`}
I don't think you need to use backticks here. Because the result of calling "t" is returning a straight string. Did this still work in testing?

2024-02-14 11:33 UTC, PeachyOmnivore requested changes
wait for lewis

2024-02-14 11:35 UTC, Uprising5034 reviewed
Looks good to me!

2024-02-14 12:32 UTC, Auenc approved these changes

2024-02-15 15:34 UTC, PeachyOmnivore approved these changes

2024-02-15 15:34 UTC, PeachyOmnivore commented on src/pages/login/index.js
> +        altButtonText={t("Registrera dig")}
spelling mistake?

2024-02-15 15:34 UTC, merged